version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: superdupersecretpassword
      MYSQL_USER: alcali
      MYSQL_PASSWORD: alcali
    volumes:
      - ./docker/sql/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      args:
        USER_ID: ${USER_ID:-1000}
    command: gunicorn config.wsgi:application -c /opt/alcali/code/docker/gunicorn_config.py
    volumes:
      - .:/opt/alcali/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    depends_on:
      - web
      - db
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: salt-minion -l info
    depends_on:
      - master
