version: '3'

services:
  db:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: salt
      MYSQL_ROOT_PASSWORD: superdupersecretpassword
      MYSQL_USER: alcali
      MYSQL_PASSWORD: alcali
    volumes:
      - ./docker/sql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  web:
    build:
      context: .
      dockerfile: ./docker/Dockerfile-dev
      args:
        USER_ID: ${USER_ID:-1000}
    command: python alcali/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/opt/alcali/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - env.dev
  master:
    build:
      context: ./docker
      dockerfile: Dockerfile-master
    command: honcho start
    depends_on:
      - web
    environment:
      - PYTHONUNBUFFERED=true
    ports:
      - "8080:8080"
  minion:
    build:
      context: ./docker
      dockerfile: Dockerfile-minion
    command: bash -c 'echo `hostname`>/etc/salt/minion_id && salt-minion -l info'
    depends_on:
      - master
