# Generated by Django 3.1.7 on 2021-04-18 10:03

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings


def add_masters(apps, schema_editor):
    Masters = apps.get_model("api", "Masters")
    for key, value in settings.SALT.items():
        Masters.objects.create(master_id=key, url=value)


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_auto_20200317_1719"),
    ]

    operations = [
        migrations.CreateModel(
            name="Masters",
            fields=[
                (
                    "master_id",
                    models.CharField(
                        default=settings.MASTERS[0], max_length=128, primary_key=True
                    ),
                ),
                ("url", models.URLField()),
            ],
            options={"db_table": "master",},
        ),
        migrations.AddField(
            model_name="keys",
            name="master",
            field=models.ForeignKey(
                default=settings.MASTERS[0],
                on_delete=django.db.models.deletion.CASCADE,
                to="api.masters",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="minions",
            name="master",
            field=models.ForeignKey(
                default=settings.MASTERS[0],
                on_delete=django.db.models.deletion.CASCADE,
                to="api.masters",
            ),
            preserve_default=False,
        ),
        migrations.RunPython(add_masters),
    ]
