# Generated by Django 4.2.4 on 2023-09-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_device_devicegroup"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="ip",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
