# Generated by Django 4.2.4 on 2023-09-04 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0005_alter_device_ip"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="minion",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="api.minions",
            ),
        ),
    ]
