FROM python:3.10-bullseye


RUN mkdir /etc/apt/keyrings

RUN curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/amd64/latest bullseye main" | tee /etc/apt/sources.list.d/salt.list
# Upgrade System and Install dependencies
RUN apt-get update && \
  apt-get upgrade -y -o DPkg::Options::=--force-confold && \
  apt-get install -y -o DPkg::Options::=--force-confold curl python3-mysqldb netcat

# Install Latest Salt from the stable Branch
# RUN curl -L https://bootstrap.saltstack.com | sh -s -- -X -M -x python3 stable latest
RUN apt-get install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api

# Set master and id
COPY saltconfig/etc/minion /etc/salt/minion
RUN echo "id: master">>/etc/salt/minion

# Install python dependencies
RUN apt-get install -y -o DPkg::Options::=--force-confold salt-api python3-openssl
RUN pip install honcho

# Copy needed files
COPY saltconfig/etc/master /etc/salt/master
COPY saltconfig/salt /srv/salt
COPY saltconfig/pillar /srv/pillar
COPY utils/wait-for .
COPY utils/Procfile .
COPY utils/entrypoint-master.sh .
# RUN mkdir /var/cache/salt/master/extmods
# RUN chmod -R a+rwx /var/cache/salt/master/extmods
# RUN chmod -R a+rwx /srv/salt/
# RUN chmod -R a+rwx /srv/salt/_returners/
# RUN chmod -R a+rwx /srv/salt/_returners/alcali.py
# # Sync auth and returners
# RUN salt-run saltutil.sync_all

# Create salt-api certs
RUN salt-call --local tls.create_self_signed_cert cacert_path='/etc/pki'
RUN chmod -R a+rwx /etc/pki/

# RUN chmod -R a+rwx /etc/pki/certs
# RUN ls -la /etc/pki/certs

ENTRYPOINT ["./entrypoint-master.sh"]
