FROM python:3.10-bullseye


RUN mkdir /etc/apt/keyrings

RUN curl -fsSL -o /etc/apt/keyrings/salt-archive-keyring-2023.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/SALT-PROJECT-GPG-PUBKEY-2023.gpg
RUN echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/amd64/latest bullseye main" | tee /etc/apt/sources.list.d/salt.list
# Upgrade System and Install dependencies
RUN apt-get update && \
  apt-get upgrade -y -o DPkg::Options::=--force-confold && \
  apt-get install -y -o DPkg::Options::=--force-confold curl python3-mysqldb netcat

# Install Latest Salt from the stable Branch
# RUN curl -L https://bootstrap.saltstack.com | sh -s -- -X -M -x python3 stable latest
RUN apt-get install -y salt-master salt-minion salt-ssh salt-syndic salt-cloud salt-api
# Set master
COPY saltconfig/etc/minion /etc/salt/minion

COPY utils/entrypoint-minion.sh .

ENTRYPOINT ["./entrypoint-minion.sh"]
