# Project Infos.
site_name: 'ALCALI'
nav:
    - Home: index.md
    - Try it!: try.md
    - Walkthrough: walkthrough.md
    - Installation: installation.md
    - Configuration: configuration.md
    - Running Alcali: running.md
    - Views:
        - 'Overview': views/overview.md
        - 'Minions': views/minions.md
        - 'Minion Details': views/minion_details.md
        - 'Jobs': views/jobs.md
        - 'Job Detail': views/job_detail.md
        - 'Run': views/run.md
        - 'Schedule': views/schedule.md
        - 'Conformity': views/conformity.md
        - 'Keys': views/keys.md
        - 'Events': views/events.md
        - 'Users': views/users.md
        - 'Settings': views/settings.md
    - Contribute: contribute.md
    - Licence: licence.md
site_description: 'A web based tool for monitoring and administrating Saltstack'
site_author: 'Matt Melquiond'

# Repository
repo_name: 'latenighttales/alcali'
repo_url: 'https://github.com/latenighttales/alcali'
edit_uri: ''

# Copyright
copyright: 'Copyright &copy; 2019 All rights reserved'

theme:
  name: 'material'
  feature:
    tabs: true
  custom_dir: 'theme'
  logo: 'images/logo-144.png'
  favicon: 'images/favicon.ico'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'indigo'
extra_css:
  - stylesheets/extra.css
extra:
  social:
    - type: 'github'
      link: 'https://github.com/latenighttales/alcali'
markdown_extensions:
  - pymdownx.inlinehilite
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
