name: Node.js Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: npm install
    - name: Build statics
      run: npm run build
    - name: Commit statics
      uses: stefanzweifel/git-auto-commit-action@v4.1.5
      with:
        file_pattern: dist/index.html dist/static/*
        commit_message: commit statics