name: Docker Compose Actions Workflow
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup env config
        run: cp env.sample .env
      - name: Install Black
        run: pip install black
      - name: Build the stack
        run: docker-compose -f docker-compose-ci.yml up -d
      - name: Test
        run: bash docker/utils/ci_script.sh
      - name: Check safety
        if: ${{ success() }}
        run: docker-compose exec -u alcali web safety check
      - name: Upload Codecov
        if: ${{ success() }}
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: docker-compose exec -u alcali -e "$env:CODECOV_TOKEN" web codecov -X s3
      - name: Show logs
        if: ${{ failure() }}
        run: docker-compose logs
